### ISSUE TITLE
After upgrading from 2.27 -> 2.34 getting run running offline

### ISSUE THREAD

**Issue by chanan** [DataDog/serverless-plugin-datadog#175]
## Expected Behavior
Runs correctly in 2.27 in offline mode. Did not try deploy

## Actual Behavior
```
yarn run v1.22.11
$ serverless offline --noAuth --noPrependStageInUrl
 
 Error ---------------------------------------------------
 
  Error: Cannot find module 'serverless/lib/plugins/aws/lib/naming'
  Require stack:
  - C:\Work\Source\marketron-api\node_modules\serverless-plugin-datadog\dist\src\forwarder.js
  - C:\Work\Source\marketron-api\node_modules\serverless-plugin-datadog\dist\src\index.js
  - C:\Users\cbraunstein\AppData\Local\Yarn\Data\global\node_modules\serverless\lib\classes\PluginManager.js
  - C:\Users\cbraunstein\AppData\Local\Yarn\Data\global\node_modules\serverless\lib\Serverless.js
  - C:\Users\cbraunstein\AppData\Local\Yarn\Data\global\node_modules\serverless\scripts\serverless.js
  - C:\Users\cbraunstein\AppData\Local\Yarn\Data\global\node_modules\serverless\bin\serverless.js
      at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
      at Function.Module._load (node:internal/modules/cjs/loader:778:27)
      at Module.require (node:internal/modules/cjs/loader:1005:19)
      at require (node:internal/modules/cjs/helpers:94:18)
      at Object.<anonymous> (C:\Work\Source\marketron-api\node_modules\serverless-plugin-datadog\dist\src\forwarder.js:13:18)
      at Module._compile (node:internal/modules/cjs/loader:1101:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
      at Module.load (node:internal/modules/cjs/loader:981:32)
      at Function.Module._load (node:internal/modules/cjs/loader:822:12)
      at Module.require (node:internal/modules/cjs/loader:1005:19)
      at require (node:internal/modules/cjs/helpers:94:18)
      at Object.<anonymous> (C:\Work\Source\marketron-api\node_modules\serverless-plugin-datadog\dist\src\index.js:45:21)
      at Module._compile (node:internal/modules/cjs/loader:1101:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
      at Module.load (node:internal/modules/cjs/loader:981:32)
      at Function.Module._load (node:internal/modules/cjs/loader:822:12)
      at Module.require (node:internal/modules/cjs/loader:1005:19)
      at require (node:internal/modules/cjs/helpers:94:18)
      at requireServicePlugin (C:\Users\cbraunstein\AppData\Local\Yarn\Data\global\node_modules\serverless\lib\classes\PluginManager.js:33:12)
      at C:\Users\cbraunstein\AppData\Local\Yarn\Data\global\node_modules\serverless\lib\classes\PluginManager.js:177:22
      at Array.map (<anonymous>)
      at PluginManager.resolveServicePlugins (C:\Users\cbraunstein\AppData\Local\Yarn\Data\global\node_modules\serverless\lib\classes\PluginManager.js:174:10)
      at PluginManager.loadAllPlugins (C:\Users\cbraunstein\AppData\Local\Yarn\Data\global\node_modules\serverless\lib\classes\PluginManager.js:157:10)
      at Serverless.init (C:\Users\cbraunstein\AppData\Local\Yarn\Data\global\node_modules\serverless\lib\Serverless.js:211:30)
      at async C:\Users\cbraunstein\AppData\Local\Yarn\Data\global\node_modules\serverless\scripts\serverless.js:557:7

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              16.8.0
     Framework Version:         2.58.0
     Plugin Version:            5.4.4
     SDK Version:               4.3.0
     Components Version:        3.17.0

Serverless: Deprecation warning: Variables resolver reports following resolution errors:
              - Cannot resolve variable at "provider.vpc": Value not found at "file" source,
              - Cannot resolve variable at "custom.datadog": Value not found at "file" source
            From a next major this will be communicated with a thrown error.
            Set "variablesResolutionMode: 20210326" in your service config, to adapt to new behavior now
            More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_VARIABLES_RESOLVER
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Steps to Reproduce the Problem

  1. Upgrade in package.json from 2.27 -> 2.34
  1. Run `yarn install`
  1. run `serverless offline --noAuth --noPrependStageInUrl`

## Specifications

 In error message above
  
## Stacktrace
  
In error message above

**Comment by astuyve** [comment]
Hi @chanan - this file is being imported from the serverless framework. It's not a dependency of the plugin, because the plugin can't be used outside of the context of the serverless framework.

Can you list the contents of `C:\Users\cbraunstein\AppData\Local\Yarn\Data\global\node_modules\serverless\lib\plugins\aws\lib`?

If `naming` doesn't exist, could you try installing the serverless framework as a development dependency? `yarn add -D serverless`?

If that works, and you're able to package/deploy with a copy of Serverless installed local in the project, could you try re-installing the system version of Serverless?

Thank you!

**Comment by chanan** [comment]
Hi @astuyve,

I stopped at your first step because `naming.js` is listed under `C:\Users\cbraunstein\AppData\Local\Yarn\Data\global\node_modules\serverless\lib\plugins\aws\lib`

**Comment by astuyve** [comment]
Okay thanks @chanan, I'll keep digging.

**Comment by astuyve** [comment]
Thanks again @chanan - this appears to be a regression introduced in #145. It can surface if `NODE_PATH` doesn't include the global node modules directory, and a user is relying on a globally installed version of the Serverless Framework.

The dependency is pretty benign anyway, so I will instead recreate the imported method.
